routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
if(!defined('STATIC_DIR')) define("STATIC_DIR","public/");
if(!defined('DEFAULT_USER')) define('DEFAULT_USER','public/icon/default-user-1.png');

//redirecting to home
Route::get('/',['middleware' => 'auth', 'uses' => 'HomeController@index']);
Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();
/**
 * Staff management
 */
Route::group(['prefix' => 'staff','as'=>'staff.'], function () {
    Route::get('/',['uses' => 'Auth\RegisterController@show','as' => 'show']);
    Route::get('/edit/{id}', ['uses' => 'Auth\RegisterController@getEdit','as' => 'edit']);
    Route::post('/edit/{id}', ['uses' => 'Auth\RegisterController@update']);
    Route::get('/view/{id}', ['uses' => 'Auth\RegisterController@getView','as' => 'view']);
    Route::post('/delete', ['uses' => 'Auth\RegisterController@delete','as' => 'delete']);
    Route::get('/role', ['uses' => 'Auth\RegisterController@editRole','as' => 'role']);
    Route::post('/role', ['uses' => 'Auth\RegisterController@updateRole']);
});

Route::get('/profile/view/{id}', ['uses' => 'ProfileController@view','as' => 'profile.view']);
Route::get('/password/edit', ['uses' => 'ProfileController@editPassword','as' => 'password.edit']);
Route::post('password/edit/{id}', ['uses' => 'ProfileController@updatePassword','as' => 'password.update']);

/**
 *  Department
 */
Route::group(['prefix' => 'department','as'=>'department.'], function () {
    Route::get('/index', ['uses' => 'DepartmentController@getIndex','as' => 'home']);
    Route::get('/', ['uses' => 'DepartmentController@create','as' => 'create']);
    Route::post('/', ['uses' => 'DepartmentController@store','as' => 'create']);
    Route::get('/edit/{id}', ['uses' => 'DepartmentController@edit','as' => 'edit']);
    Route::post('/edit/{id}', ['uses' => 'DepartmentController@update']);
});

/**
 *  Task management
 */
Route::group(['prefix' => 'task','as'=>'task.'], function () {
    Route::get('/create', ['uses' => 'TaskController@create','as' => 'create'])->middleware(['auth','admin']);
    Route::post('/create', ['uses' => 'TaskController@store','as' => 'store'])->middleware(['auth','admin']);
    Route::get('/show', ['uses' => 'TaskController@show','as' => 'show'])->middleware(['auth']);
    Route::get('/completed', ['uses' => 'TaskController@showCompletedTask','as' => 'show_completed_task'])->middleware(['auth']);

    Route::get('/assign', ['uses' => 'TaskController@getAssign','as' => 'assign'])->middleware(['auth','admin']);
    Route::post('/assign', ['uses' => 'TaskController@assign','as' => 'assign'])->middleware(['auth','admin']);
    Route::get('/assign/id', ['uses' => 'TaskController@getAssignedUserById','as' => 'getUserByTaskId'])->middleware(['auth','admin']);


    Route::get('/view/{id}',['uses' => 'TaskController@viewTask','as' => 'view']);
    Route::get('/status/{id}', ['uses' => 'TaskController@status','as' => 'status']);
    Route::get('/edit/{id}', ['uses' => 'TaskController@edit','as' => 'edit'])->middleware(['auth','admin']);
    Route::post('/edit/{id}', ['uses' => 'TaskController@update'])->middleware(['auth','admin']);
    Route::post('/delete', ['uses' => 'TaskController@delete','as' => 'delete'])->middleware(['auth','admin']);

    //change task status plus add remarks.
    Route::post('/remarks/store', ['uses' => 'TaskController@addRemarks', 'as' => 'store_remarks'])->middleware(['auth']);

    //get task  from usre id
    Route::get('/user/task',['uses' => 'TaskController@getTaskByUserId', 'as' => 'user-task']);

    //client routes
    Route::get('/client/show',['uses' => 'TaskController@getAllClient', 'as' => 'client-retrieve'])->middleware(['auth','admin']);
    Route::post('/client/add', ['uses' => 'TaskController@storeClient','as' => 'client-store'])->middleware(['auth','admin']);
    Route::post('/client/delete', ['uses' => 'TaskController@deleteClient','as' => 'client-delete'])->middleware(['auth','admin']);

    Route::post('/client/retrieve/clientinfo',['uses' => 'TaskController@getClientById', 'as' => 'client-retrieve-id'])->middleware(['auth','admin']);
    Route::post('/client/edit', ['uses' => 'TaskController@editClient','as' => 'client-edit'])->middleware(['auth','admin']);



});


/**
 *  Search
 */
Route::post('/result', ['uses' => 'SearchController@getResult','as' => 'search.result']);

Route::get('/list', ['uses' => 'SearchController@list']);

/**
 * Comment
 */
Route::post('/comment/{taskId}', ['uses' => 'CommentController@store','as' => 'comment']);

Route::get('/comment/delete/{id}', ['uses' => 'CommentController@delete','as' => 'comment.delete']);

Route::get('/comment/update/{id}', ['uses' => 'CommentController@edit','as' => 'comment.update']);

Route::post('/comment/update/{id}', ['uses' => 'CommentController@update','as' => 'comment.update']);



/**
 * Telephone Directory
 */
Route::group(['prefix' => 'telephone','as' => 'telephone.'],function(){
   Route::get('/',['uses' => 'TelephoneController@index', 'as' => 'index']);
   Route::get('/register',['uses' => 'TelephoneController@registerTelephone', 'as' => 'register_telephone']);
   Route::post('/register',['uses' => 'TelephoneController@postRegisterTelephone', 'as' => 'register_telephone']);

   //edit telephone
    Route::get('/edit/{id}',['uses' => 'TelephoneController@editTelephone', 'as' => 'edit_telephone']);
    Route::post('/update',['uses' => 'TelephoneController@postEditTelephone', 'as' => 'update_telephone']);

    //delete telephone information
    Route::post('/delete',['uses' => 'TelephoneController@deleteTelephone', 'as' => 'delete_telephone']);


});

/**
 * Application Leave
 */
Route::group(['prefix' => 'leave','as' => 'leave.'],function(){
   Route::get('/',['uses' => 'LeaveController@index', 'as' => 'list']);
   Route::get('/application/fill',['uses' => 'LeaveController@registerLeave', 'as' => 'register_leave']);
   Route::post('/register',['uses' => 'LeaveController@postRegisterLeave', 'as' => 'store_leave']);

   //edit telephone
    Route::get('/edit/{id}',['uses' => 'LeaveController@editTelephone', 'as' => 'edit_telephone']);
    Route::post('/update',['uses' => 'LeaveController@postEditTelephone', 'as' => 'update_telephone']);

    //delete telephone information
    Route::post('/delete',['uses' => 'LeaveController@deleteTelephone', 'as' => 'delete_telephone']);


});

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $fillable = [
        'name',
    ];

    public function users()
    {
        return $this->belongsToMany(User::class);
    }

    public function author()
    {
        return $this->belongsTo('App\User', 'created_by')->select(array('id', 'full_name'));
    }

    public function clients()
    {
        return $this->belongsTo('App\Client', 'client_id')->select(array('id', 'name','number'));
    }


    public function comments()
    {
        return $this->hasMany('App\Comment');
    }
}

app/Http/Controllers/Api/TaskController.php
<?php

namespace App\Http\Controllers\Api;

use App\Client;
use App\Helper\Tools;
use App\Task;
use App\TaskNotification;
use App\TaskRemark;
use App\TaskUser;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class TaskController extends Controller
{
    public function clientList(){
        $data['client'] = Client::orderby('id','desc')->get();

        $responseData = Tools::setResponse('success','Client Listed Successfully', $data,'');
        return response()->json($responseData,200);
    }


    public function storeTask(Request $request)
    {

        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'status' => 'required',
            'priority' => 'required',
            'client_id'=> 'required',
            'deadline' => 'required|numeric',
            'staff' => 'required',
            'created_by' => 'required'
        ]);


        if ($validator->fails()) {
            $responseData = Tools::setResponse('fail', 'Missing Parameter', '', '');
            $status = 422;
            return response()->json($responseData, $status);
        }

        //adding new task

        $task = new Task;
        $task->name = $request->name;
        $task->deadline = date('Y-m-d', strtotime("+" . $request->deadline . " days"));
        $task->description = $request->description;

        $task->priority = $request->priority;
        $task->task_type = $request->task_type;

        $task->client_id= $request->client_id;


        $task->created_at = date('Y-m-d H:i:s');
        $task->created_by = $request->created_by;
        $task->save();

        //adding assigned staff to relationship
        //retrieve json encode employee id

        $decodedArray = json_decode($request->staff,true);
        $staff_id = array();

        foreach ($decodedArray['staff'] as $value) {
            $staff_id[] = $value['staff_id'];
        }

        // attached staff info from user table in the task found above
        $task->users()->sync($staff_id, false);


        //sending notification to the assigned staff about the new task

        if (isset($request->staff)) {
            //retrieve assigned user.
            $assigned_user = array();

            foreach ($staff_id as $value) {
                $assigned_user[] = User::find($value);
            }

            foreach ($assigned_user as $value) {
                $this->notification($value->firebase_token, $request->title, $request->description);

                $notification = new TaskNotification();
                $notification->name = $request->name;
                $notification->user_id = $value->id;
                $notification->description = $request->description;
                $notification->save();
            }


        }

        $responseData = Tools::setResponse('success','Task Added Successfully', '','');
        return response()->json($responseData,200);
    }

    public function changeStatus(Request $request){
        $validator = Validator::make($request->all(), [
            'task_id' => 'required',
            'status' => 'required'
        ]);

        if ($validator->fails()) {
            $responseData = Tools::setResponse('fail','Missing Parameter', '','');
            $status = 422;
            return response()->json($responseData,$status);

        }


//        if(isset($request->remarks)){
        $remarks = new TaskRemark();
        $remarks->task_id = $request->task_id;
        $remarks->remarks = $request->remarks;
        $remarks->status = $request->status;
        $remarks->save();
//        }

        //upload file in server folder.
        $task = Task::find($request->task_id);

        if(isset($request->file_upload)){
            $upload = $request->file('file_upload')->store('files/'.$request->task_id.'/completed_task', 'public');
            $task->file = $upload;

        }

        $task->status = $request->status;
        $task->save();


        if(isset($request->file_upload)){
            $responseData = Tools::setResponse('success','Status Changed Successfully with remarks and File Upload', '','');
            $status = 200;
        }
        else if(isset($request->remarks)){
            $responseData = Tools::setResponse('success','Status Changed Successfully with remarks.', '','');
            $status = 200;
        }
        else{
            $responseData = Tools::setResponse('success','Status Changed Successfully', '','');
            $status = 200;
        }

        return response()->json($responseData,$status);
    }

    public function getTaskByUserId(){

        if(!isset($_GET['user_id'])){
            $responseData = Tools::setResponse('fail','Missing Parameter', '','');
            $status = 422;
            return response()->json($responseData,$status);
        }

        $user_id =$_GET['user_id'];
        //fetching all task except completed one.
        $user = User::where('id',$user_id)->with('whereTask.author')->with('whereTask.clients')->first();
        $user->makeHidden(['contact','email','permanent_address','temporary_address','facebook_link','google_link','twitter_link']);

        //count task on open append and completed.
        /*$task = Task::all();
        $count['new'] = $task->where('status',0)->count();
        $count['opened'] = $task->where('status',1)->count();
        $count['pending'] = $task->where('status',2)->count();
        $count['completed'] = $task->where('status',3)->count();*/

        $responseData = Tools::setResponse('success','Task Listing Based on Assigned User Successful.', $user,'');
        $status = 200;

        return response()->json($responseData,$status);
    }

    public function getTaskByStatus(Request $request){
        if(!isset($request->user_id) || !isset($request->limit) || !isset($request->status)){
            $responseData = Tools::setResponse('fail','Missing Parameter', '','');
            $status = 422;
            return response()->json($responseData,$status);
        }

        //accessing get values
        $user_id = $request->user_id;
        $limit = $request->limit;
        $status = $request->status;

//        note: if client id is deleted all the data are not retrieved
        $task = TaskUser::select('t.id', 't.name', 't.status','t.file','t.deadline','t.description','c.name as client_name','c.number as client_number','u.full_name as author','t.created_at','t.deadline','t.priority')
            ->leftjoin('tasks as t','task_user.task_id','t.id')
            ->leftjoin('users as u','u.id','t.created_by')
            ->leftjoin('clients as c','c.id','t.client_id')
            ->where('user_id',$user_id)
            ->where('t.status',$status)
            ->paginate($limit);

        $responseData = Tools::setResponse('success','Fetch New Task based on user id successfull.', $task,'');
        $status = 200;

        return response()->json($responseData,$status);

    }

    public function countTaskByStatus(Request $request){
        if(!isset($request->user_id)){
            $responseData = Tools::setResponse('fail','Missing Parameter', '','');
            $status = 422;
            return response()->json($responseData,$status);
        }

        $user_id =$request->user_id;
        //fetching all task except completed one.
        $user = User::where('id',$user_id)->with('tasks')->first();

        //count task on new, open, append and completed.
        $count['new'] = $user->tasks->where('status',0)->count();
        $count['opened'] = $user->tasks->where('status',1)->count();
        $count['pending'] = $user->tasks->where('status',2)->count();
        $count['completed'] = $user->tasks->where('status',3)->count();

        $responseData = Tools::setResponse('success','Task Counting on User Id Completed', $count,'');
        $status = 200;

        return response()->json($responseData,$status);
    }


    public function notification($token, $title,$description = null)
    {
        $fcmUrl = 'https://fcm.googleapis.com/fcm/send';
        $token=$token;

        $notification = [
            'title' => ucfirst($title),
            'text' => $description,
//            'assigned_by' => 'yonzon',
            // 'sound' => true,
             'sound' => "notification.mp3",
        ];

        $extraNotificationData = ["message" => $notification,"moredata" =>'dd'];

        $fcmNotification = [
            'to'        => $token, //single token
            'notification' => $notification,
            'data' => $extraNotificationData
        ];

        $headers = [
            'Authorization: key= AAAA8iYzy1M:APA91bFgJiofpoZ_zn9xCGNHP8d16EAQw-hMKCB0X1pkJbi1DYX7Jr8_6WrETFXob8BWfuCUluUBqQfiRySDNj3egAxP4PtsHnOS1fp4HPnSOAjGV2kz377BiY32VJLYxkvw1c7rVDtS',
            'Content-Type: application/json'
        ];


        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL,$fcmUrl);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($fcmNotification));
        $result = curl_exec($ch);

        if ($result === FALSE) {
            die('Curl failed: ' . curl_error($ch));
        }



        curl_close($ch);

        return true;
    }




}

resources/views/pages/task/assign.blade.php
@extends('layouts.app')
@section('page-title')
    Assign Task
@stop
@section('css')
    {{--<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />--}}
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
	        <form class="form-horizontal" role="form" method="POST" action="{{ route('task.assign') }}">
		        <div class="white-box">
			        <div class="row">
				        <div class="col-md-12">
					        {{ csrf_field() }}
							<hr>
							<p>Information of Employee and Task</p>
							<hr>
					        <div class="form-body">

								<div class="form-group">
									<label class="col-md-3 control-label">Select Employees</label>
									<div class="col-md-3">
										<select class="form-control" name="task" id="select_employee" >
											<option value="0" >-- SELECT ONE --</option>
											@if (!empty($task))
												@foreach ($staff as $data)
													<option value={{ $data->id }}>{{ $data->full_name }}</option>

												@endforeach
											@endif

										</select>
									</div>
								</div>

								<div class="form-group" id="assigned_task" style="display: none;">
									<label class="col-md-3 control-label">Assigned Tasks</label>

									<div class="col-md-9" style="margin-left: 380px; margin-top:-35px;" >
										<ol id="appendTask">
										</ol>
									</div>
								</div>

					        </div>
				        </div>

						<div class="col-md-12">
							<hr>
							<p>Assign  Task To Employee</p>
							<hr>
							<div class="col-md-8">
								<div class="form-group">
									<label class="col-md-3 control-label">Select Task</label>
									<div class="col-md-9">
										<select class="form-control" name="task" id="task">
											<option value="0" >-- SELECT ONE --</option>
											@if (!empty($task))
												@foreach ($task as $data)
													<option value={{ $data->id }}>{{ $data->name }}</option>

												@endforeach
											@endif
										</select>
									</div>
								</div>

								<div class="form-group" id="assigned_employee" style="display: none;">
									<label class="col-md-3 control-label">Assigned Employee</label>

									<div class="col-md-9" style="margin-left: 250px; margin-top:-35px;" >
										<ol id="append">
										</ol>
									</div>
								</div>

							</div>

							<div class="col-md-4">
								<div class="portlet box green-meadow">
									<div class="portlet-title">
										<div class="caption">
											<i class="fa fa-gift"></i>Employee
										</div>

									</div>
									<div class="portlet-body" style="overflow-y: scroll; height: 67vh;">

										<ul class="list-group">
											<li class="list-group-item">
												@foreach ($staff as $name)
													<div class="input-group form-control">
														<input type="checkbox" class="assigned_user"
															   aria-label="..." name="staff[]"  value="{{ $name->id }}" multiple="multiple" class="form-control-sm"
                                                        <?php /*echo ($name->id == 1) ?  "checked" : '' */?>>
														<strong>
															{{ $name->full_name }}
														</strong>
													</div>
													<br>

												@endforeach

											</li>

										</ul>
									</div>
								</div>
							</div>
						</div>
			        </div>
		        </div>

		       <div class="white-box">
			       <div class="row">
				       <div class="col-md-12">
					       <div class="form-actions">
						       <a href="{{ URL::previous() }}" type="button" class="btn default">Cancel</a>
						       <button type="submit" class="btn green">Assign</button>
					       </div>
				       </div>
			       </div>
		       </div>
	        </form>
        </div>
    </div>
@endsection

@section('script')
    {{--<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>--}}

    <script>
        $(document).ready(function() {
            let user = $('.assigned_user').val();
            console.log(user);
            // alert(user);
        });

        $(document).ready(function (){
            $("#task").on ('change',  function( e ){
                let task_id = $('#task').val();
                $("#append").children("li").remove();


                if(task_id == 0){
                    $('#assigned_employee').hide();

                }
                else{
					//retrieving assigned user from task id.
                    $.ajax({
                        type: "GET",
                        url: "{{ route('task.getUserByTaskId') }}",
                        headers: {
                            'XCSRFToken': $('meta[name="csrftoken"]').attr('content')
                        },

                        data: "id=" + task_id,
                        success: function (msg) {
                            $('#assigned_employee').show();
                            appendlist(msg.data);
                        }
                    });
				}


            });

            $("#select_employee").on ('change',  function( e ){
                let user_id = $(this).val();
                $("#appendTask").children("li").remove();

                if(user_id == 0){
                    $('#assigned_task').hide();
                }
                else{
                    //retrieving assigned user from task id.
                    $.ajax({
                        type: "GET",
                        url: "{{ route('task.user-task') }}",
                        headers: {
                            'XCSRFToken': $('meta[name="csrftoken"]').attr('content')
                        },

                        data: "user_id=" + user_id,
                        success: function (msg) {
                            $('#assigned_task').show();
                            appendTask(msg);

                        }
                    });
				}

            });

        });


        function appendlist(data) {

            $.each(data.users, function () {
                $("#append").append("&nbsp;<li>" + this.full_name +"</li>");
                // $(".assigned_user").prop("checked",true);

            });
        }

        function appendTask(data){
            $.each(data, function (value, key) {
                $("#appendTask").append("&nbsp;<li>" + this.name +"</li>");
            });
		}


    </script>
@endsection

resources/views/pages/task/completed_task.blade.php
@extends('layouts.app')
@section('page-title')
    Task Listing
@stop
@section('css')
    <link rel="stylesheet" href="{{ asset(STATIC_DIR.'css/jquery.dataTables.min.css') }}">
    <link href="{{ asset(STATIC_DIR.'css/style.css')}}" rel="stylesheet" type="text/css"/>
@stop

@section('content')
    <div class="white-box">
        <div class="row" style="min-height: 83vh !important;">
            <div class="col-lg-12">
                <div class="main-box clearfix">
                    <div class="table-responsive" >
                        <table class="table table-striped table-bordered" id="myTable">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Title</th>
                                <th>Assigned to</th>
                                <th>Assigned By</th>
                                <th>Created At</th>
                                <th>Status</th>
                                <th>Deadline</th>
                                <th>Task Priority</th>
                                <th class="col-sm-2"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @if(isset($task))
                                @foreach($task->sortBy('status',0) as $val)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>
                                            @if(strlen($val->name) >30)
                                            {{substr($val->name,0,50)}}
                                            </br>
                                            {{substr($val->name,50,strlen($val->name))}}

                                            @else
                                                {{$val->name}}
                                            @endif
                                        </td>
                                        <td>
                                            @if($val->users->count() == 0)
                                                <strong>No Staffs Assigned</strong>
                                            @else
                                                @foreach($val->users as $value)
                                                    <p>{{$value->full_name}}</p>
                                                @endforeach
                                            @endif
                                        </td>

                                        <td>
                                            <p>{{$val->author->full_name}}</p>
                                            {{--@foreach($val->author as $value)--}}
                                            {{--<p>{{$value->full_name}}</p>--}}
                                            {{--@endforeach--}}
                                        </td>

                                        <td>{{ $val->created_at->diffForHumans() }}</td>

                                        <td class="center">
                                            @if($val->status==0)
                                                <p class="list-group-item-text">
                                                    <span class="label label-primary">New</span>
                                                </p>
                                            @elseif($val->status==1)
                                                <p class="list-group-item-text">
                                                    <span class="label label-warning">Opened</span>
                                                </p>
                                            @elseif($val->status==2)
                                                <p class="list-group-item-text">
                                                    <span class="label label-danger">Pending</span>
                                                </p>
                                            @elseif($val->status==3)
                                                <p class="list-group-item-text">
                                                    <span class="label label-success">Completed</span>
                                                </p>
                                            @endif
                                        </td>
                                        <td>
                                            {{$val->deadline}}
                                        </td>

                                        <td>
                                            @if($val->priority == 1)
                                                <span class="label label-default">Normal</span>
                                            @elseif($val->priority == 2)
                                                <span class="label label-warning">Important</span>
                                            @else
                                                <span class="label label-danger">Urgent</span>
                                            @endif
                                        </td>

                                        <td style="width: 12%;" >

                                            <a href="{{ route('task.view',$val->id) }}" class="table-link" title="View details">
                                                <span class="fa-stack">
                                                    <i class="fa fa-square fa-stack-2x" ></i>
                                                    <i class="fa fa-eye fa-stack-1x fa-inverse"></i>
                                                </span>
                                            </a>

                                            <a href="{{ route('task.edit',$val->id) }}" class="table-link" title="Edit">
                                                <span class="fa-stack">
                                                    <i class="fa fa-square fa-stack-2x"></i>
                                                    <i class="fa fa-pencil fa-stack-1x fa-inverse"></i>
                                                </span>
                                            </a>

                                            <a href="{{ route('task.delete',$val->id) }}" data-key="" class="table-link danger delete" title="Delete">
                                                <span class="fa-stack">
                                                    <i class="fa fa-square fa-stack-2x"></i>
                                                    <i class="fa fa-trash-o fa-stack-1x fa-inverse"></i>
                                                </span>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script type="text/javascript" src="{{ asset(STATIC_DIR.'jquery/jquery.dataTables.min.js') }}"></script>
    <script>
        $(document).ready( function () {
            $('#myTable').dataTable( {
                "pageLength": 50,
                "lengthMenu": [ 10, 25, 50, 75, 100 ]
            } );
        } );
    </script>
@endsection

resources/views/pages/task/editComment.blade.php
@extends('layouts.app')

@section('content')

	<h3>Comments</h3>
			<div class="default-row-spacer">
    				<div class="row">
    					<div class="col-md-12">
    						<div class="widget-area no-padding blank">
								<div class="status-upload">
									<form action="{{ route('comment.update',$comment->id) }}" method="post">
									{{ csrf_field() }}
										<textarea placeholder="Write a comment for this task?" name="comment_edit" >{{ $comment->comment }}</textarea>
										<ul>
											<li><a title="" data-toggle="modal" data-target="#myModal3" data-placement="bottom" data-original-title="Audio"><i class="fa fa-upload"></i></a></li>
										</ul>
										<button type="submit" class="btn btn-success green"><i class="fa fa-share"></i> Update</button>
									</form>
								</div><!-- Status Upload  -->
							</div><!-- Widget Area -->
						</div>
				</div>
			</div>

@endsection