routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
if(!defined('STATIC_DIR')) define("STATIC_DIR","public/");
if(!defined('DEFAULT_USER')) define('DEFAULT_USER','public/icon/default-user-1.png');

//redirecting to home
Route::get('/',['middleware' => 'auth', 'uses' => 'HomeController@index']);
Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();
/**
 * Staff management
 */
Route::group(['prefix' => 'staff','as'=>'staff.'], function () {
    Route::get('/',['uses' => 'Auth\RegisterController@show','as' => 'show']);
    Route::get('/edit/{id}', ['uses' => 'Auth\RegisterController@getEdit','as' => 'edit']);
    Route::post('/edit/{id}', ['uses' => 'Auth\RegisterController@update']);
    Route::get('/view/{id}', ['uses' => 'Auth\RegisterController@getView','as' => 'view']);
    Route::post('/delete', ['uses' => 'Auth\RegisterController@delete','as' => 'delete']);
    Route::get('/role', ['uses' => 'Auth\RegisterController@editRole','as' => 'role']);
    Route::post('/role', ['uses' => 'Auth\RegisterController@updateRole']);
});

Route::get('/profile/view/{id}', ['uses' => 'ProfileController@view','as' => 'profile.view']);
Route::get('/password/edit', ['uses' => 'ProfileController@editPassword','as' => 'password.edit']);
Route::post('password/edit/{id}', ['uses' => 'ProfileController@updatePassword','as' => 'password.update']);

/**
 *  Department
 */
Route::group(['prefix' => 'department','as'=>'department.'], function () {
    Route::get('/index', ['uses' => 'DepartmentController@getIndex','as' => 'home']);
    Route::get('/', ['uses' => 'DepartmentController@create','as' => 'create']);
    Route::post('/', ['uses' => 'DepartmentController@store','as' => 'create']);
    Route::get('/edit/{id}', ['uses' => 'DepartmentController@edit','as' => 'edit']);
    Route::post('/edit/{id}', ['uses' => 'DepartmentController@update']);
});

/**
 *  Task management
 */
Route::group(['prefix' => 'task','as'=>'task.'], function () {
    Route::get('/create', ['uses' => 'TaskController@create','as' => 'create'])->middleware(['auth','admin']);
    Route::post('/create', ['uses' => 'TaskController@store','as' => 'store'])->middleware(['auth','admin']);
    Route::get('/show', ['uses' => 'TaskController@show','as' => 'show'])->middleware(['auth']);
    Route::get('/completed', ['uses' => 'TaskController@showCompletedTask','as' => 'show_completed_task'])->middleware(['auth']);

    Route::get('/assign', ['uses' => 'TaskController@getAssign','as' => 'assign'])->middleware(['auth','admin']);
    Route::post('/assign', ['uses' => 'TaskController@assign','as' => 'assign'])->middleware(['auth','admin']);
    Route::get('/assign/id', ['uses' => 'TaskController@getAssignedUserById','as' => 'getUserByTaskId'])->middleware(['auth','admin']);


    Route::get('/view/{id}',['uses' => 'TaskController@viewTask','as' => 'view']);
    Route::get('/status/{id}', ['uses' => 'TaskController@status','as' => 'status']);
    Route::get('/edit/{id}', ['uses' => 'TaskController@edit','as' => 'edit'])->middleware(['auth','admin']);
    Route::post('/edit/{id}', ['uses' => 'TaskController@update'])->middleware(['auth','admin']);
    Route::post('/delete', ['uses' => 'TaskController@delete','as' => 'delete'])->middleware(['auth','admin']);

    //change task status plus add remarks.
    Route::post('/remarks/store', ['uses' => 'TaskController@addRemarks', 'as' => 'store_remarks'])->middleware(['auth']);

    //get task  from usre id
    Route::get('/user/task',['uses' => 'TaskController@getTaskByUserId', 'as' => 'user-task']);

    //client routes
    Route::get('/client/show',['uses' => 'TaskController@getAllClient', 'as' => 'client-retrieve'])->middleware(['auth','admin']);
    Route::post('/client/add', ['uses' => 'TaskController@storeClient','as' => 'client-store'])->middleware(['auth','admin']);
    Route::post('/client/delete', ['uses' => 'TaskController@deleteClient','as' => 'client-delete'])->middleware(['auth','admin']);

    Route::post('/client/retrieve/clientinfo',['uses' => 'TaskController@getClientById', 'as' => 'client-retrieve-id'])->middleware(['auth','admin']);
    Route::post('/client/edit', ['uses' => 'TaskController@editClient','as' => 'client-edit'])->middleware(['auth','admin']);



});


/**
 *  Search
 */
Route::post('/result', ['uses' => 'SearchController@getResult','as' => 'search.result']);

Route::get('/list', ['uses' => 'SearchController@list']);

/**
 * Comment
 */
Route::post('/comment/{taskId}', ['uses' => 'CommentController@store','as' => 'comment']);

Route::get('/comment/delete/{id}', ['uses' => 'CommentController@delete','as' => 'comment.delete']);

Route::get('/comment/update/{id}', ['uses' => 'CommentController@edit','as' => 'comment.update']);

Route::post('/comment/update/{id}', ['uses' => 'CommentController@update','as' => 'comment.update']);



/**
 * Telephone Directory
 */
Route::group(['prefix' => 'telephone','as' => 'telephone.'],function(){
   Route::get('/',['uses' => 'TelephoneController@index', 'as' => 'index']);
   Route::get('/register',['uses' => 'TelephoneController@registerTelephone', 'as' => 'register_telephone']);
   Route::post('/register',['uses' => 'TelephoneController@postRegisterTelephone', 'as' => 'register_telephone']);

   //edit telephone
    Route::get('/edit/{id}',['uses' => 'TelephoneController@editTelephone', 'as' => 'edit_telephone']);
    Route::post('/update',['uses' => 'TelephoneController@postEditTelephone', 'as' => 'update_telephone']);

    //delete telephone information
    Route::post('/delete',['uses' => 'TelephoneController@deleteTelephone', 'as' => 'delete_telephone']);


});

/**
 * Application Leave
 */
Route::group(['prefix' => 'leave','as' => 'leave.'],function(){
   Route::get('/',['uses' => 'LeaveController@index', 'as' => 'list']);
   Route::get('/application/fill',['uses' => 'LeaveController@registerLeave', 'as' => 'register_leave']);
   Route::post('/register',['uses' => 'LeaveController@postRegisterLeave', 'as' => 'store_leave']);

   //edit telephone
    Route::get('/edit/{id}',['uses' => 'LeaveController@editTelephone', 'as' => 'edit_telephone']);
    Route::post('/update',['uses' => 'LeaveController@postEditTelephone', 'as' => 'update_telephone']);

    //delete telephone information
    Route::post('/delete',['uses' => 'LeaveController@deleteTelephone', 'as' => 'delete_telephone']);


});

resources/views/pages/staff/modal.blade.php
<div id="showMessage" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content" style="margin-top: 200px;">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title"><i class="fa fa-info-circle" id="icon-terminate" ></i> User Deleted
                </h4>
            </div>

            <div class="modal-body">
                <div class="error" style="display: none;">
                    <i class="fa fa-close"></i> &nbsp; Error While Deleting &nbsp;Staff Information .
                </div>

                <div class="success" style="display: none;">
                    <i class="fa fa-check"></i> &nbsp; Staff Information Deleted Successfully .
                </div>

            </div>
            <input type="hidden" id="hidden_id">
            <div class="modal-footer" style="text-align: center;">
                <button type="button" class="btn btn-danger green confirm_yes" id="show_message"><i class="icon-check"></i> Ok
                </button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
</div>

<div id="deleteStaff" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content"  style="margin-top: 200px;">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title"><i class="fa fa-info-circle" id="icon-terminate" ></i> Delete Permanently
                </h4>
            </div>
            <div class="modal-body"> Do you want to delete <span class='hidden_title'>" "</span>?</div>
            <input type="hidden" id="hidden_id">
            <div class="modal-footer">
                <button type="button" class="btn btn-danger green confirm_yes" id="confirm_yes"><i class="icon-check"></i> Yes
                </button>
                <button type="button" class="btn btn-default" data-dismiss="modal"><i class="icon-close" id="icon-terminate"></i>
                    No
                </button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
</div>

resources/views/pages/staff/password.blade.php
@extends('layouts.app')
@section('content')
           <br>
          <div class="container">
          	<div class="row">
           <div class="col-md-4 ">
           <form action="{{ route('password.update',Auth::user()->id) }}" method='POST'>
           	{{ csrf_field() }}
               <div class="form-group">
                   <label for="" class="control-label">
                       Old Password
                   </label>
                   <input type="password" name="old_password" id="" class="form-control" placeholder="Enter your current password.">
                   @if($errors->has('old_password'))
                       <span class="help-block">
                            <strong style="color:red;">{{ $errors->first('old_password') }}</strong>
                       </span>
                    @endif
               </div>

               <div class="form-group">
                   <label for="" class="control-label">
                       New password
                   </label>
                   <input type="password" name="password" id="" class="form-control" placeholder="Enter New Password.">
                   @if($errors->has('password'))
                       <span class="help-block">
                            <strong style="color:red;">{{ $errors->first('password') }}</strong>
                       </span>
                   @endif
               </div>

               <div class="form-group">
                   <label for="" class="control-label">
                       Confirm New password
                   </label>
                   <input type="password" name="password_c" id="" class="form-control" placeholder="Enter Again New Password.">
               </div>

               <div class="form-group">
                       <input type="submit" value="Change" class="btn btn-success">
               </div>

           </form>
           </div>
           </div>
          </div>


@endsection

resources/views/pages/staff/profile.blade.php
@extends('layouts.app')
@section('content')
	<div class="row">
		<div class="col-lg-3 col-md-3 hidden-sm hidden-xs">
			<div class="panel panel-default" >
				<div class="panel-body" style="min-height: 45vh">
					<div class="media" style="margin-top: 15px;">
						<div align="center">
							<img class="thumbnail img-responsive" src="
							     @if($profile->profile_image == null)
							{{ asset(STATIC_DIR.'images/default.jpg') }}
							@else
							{{ asset(STATIC_DIR.'storage/'.$profile->profile_image) }}
							@endif " width="300px" height="300px">
						</div>
						<div class="media-body">
							<hr>
							<p><strong>Joined date: </strong> {{ $profile->join_date ?? '' }}</p>
							<hr>
							<p><strong>Contact Number: </strong> {{ $profile->contact }}</p>
							<hr>
							<p><strong>Permanent Address: </strong> {{ $profile->permanent_address }}</p>
							<hr>
							<p><strong>Temporary Address: </strong> {{ $profile->temporary_address }}</p>
							<hr>
							<p><strong>Email Address: </strong> {{ $profile->email }}</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
			<div class="row">
				<div class="col-md-12">
					<div class="panel panel-white post panel-shadow" >
						<div class="panel-body">
							<h1 class="panel-title pull-left" style="font-size:30px;">{{ $profile->full_name }}</h1>
							<a class="btn btn-link btn-sm" href="{{ route('password.edit') }}">Change password</a>
							<a class="btn btn-link btn-sm" href="{{ route('staff.edit', Auth::user()->id) }}"> Edit profile</a>
							<i class="fa fa-gear fa-fw"></i>
							<br><br>
							<strong><small>({{ $profile->user_name }})</small>  </strong>
							<br><hr>
							
							<div class="col-md-12">
								<ul class="social-network social-circle">
									<li><a href="{{ $profile->facebook_link }}" target="_blank" class="icoFacebook" style="padding-top: 10px;" title="Facebook"><i class="fa fa-facebook"></i></a></li>
									<li><a href="{{ $profile->google_link }}" target="_blank" class="icoTwitter" title="Twitter" style="padding-top: 10px;"><i class="fa fa-twitter"></i></a></li>
									<li><a href="{{ $profile->twitter_link }}" target="_blank" class="icoGoogle" title="Google +" style="padding-top: 10px;"><i class="fa fa-google-plus"></i></a></li>
									<li><a href="{{ $profile->linkedin_link }}" target="_blank" class="icoLinkedin" title="Linkedin" style="padding-top: 10px;"><i class="fa fa-linkedin"></i></a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="white-box">
				<div class="row" style="min-height: 44vh">
					<div class="col-md-12">
						<div class="table-responsive">
							<table class="table table-bordered table-hover table-striped">
								<thead>
								<tr>
									<th style="width: 70px;">Task ID</th>
									<th>Title</th>
									<th>Created At</th>
									<th>Action</th>
								</tr>
								</thead>
								<tbody>
								@if ($assigned_completed->count()>0)
									@foreach($assigned_completed as $COMPLETED)
										<tr>
											<td>{{ $COMPLETED->id }}</td>
											<td>{{ $COMPLETED->name }}</td>
											<td>{{ $COMPLETED->created_at }}</td>
											<td>
												<a href="{{ route('task.view',$COMPLETED->id) }}" class="btn btn-default btn-block">View</a>
											</td>
										</tr>
									@endforeach
								@else
									<tr>
										<td colspan="4" class="text-center">No items found.</td>
									</tr>
								@endif
								</tbody>
							</table>
						</div>
					
					</div>
				</div>
			</div>
		</div>

@endsection

resources/views/pages/staff/role.blade.php
@extends('layouts.app')

@section('content')
  <!-- Page Heading -->
           <br>

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
        <div class="alert-danger"><strong>Type '1' to give user Administrator previllage Or '0' to give User previllage</strong></div>
           <div class="table-responsive">
                <table class="table table-bordered table-hover table-striped">
                    <tr>
                        <th>Name</th>
                        <th>Role</th>
                        <th>Action</th>
                    </tr>@foreach ($staff as $data)
                    <tr>
                    
                        @if ($data->full_name!='Administrator')
                        <form class="form-horizontal" method="post" action="{{ route('staff.role',$data->id) }}">
                            {{ csrf_field() }} 
                            <td>{{ $data->full_name }}</td>
                            <td>
                                <input type="number" name="user_type" value="{{ $data->user_type }}" class="form-control">
                            </td>
                            <td>
                                <input type="submit"  value="Change" class="btn btn-default">
                            </td>
                        </form>
                            @endif
                       
                    </tr> @endforeach
                </table>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/pages/staff/showstaff.blade.php
@extends('layouts.app')
@section('page-title')
    Staff Listing
@stop
@section('css')
    <link href="{{ asset(STATIC_DIR.'css/style.css')}}" rel="stylesheet" type="text/css"/>
@stop
@section('content')
    <div class="white-box">
        <div class="row">
            <div class="col-lg-12">
                <div class="main-box clearfix">
                    <div class="table-responsive">
                        <table class="table user-list table-hover table-bordered">
                            <thead>
                                <tr>
                                    <th><span>Users</span></th>
                                    <th><span>Username</span></th>
                                    <th><span>User Type</span></th>
                                    <th><span>Last Login</span></th>
                                    <th><span>Action</span></th>
                                </tr>
                            </thead>

                            <tbody>
                            @if(isset($staff))
                                @foreach($staff as $val)
                                    <tr>
                                        <td>
                                            @if(!empty($val->profile_image))
                                                <img src="{{ asset(STATIC_DIR.'storage/'. $val->profile_image) }}" alt=""/>
                                            @else
                                                <img src="{{ asset(DEFAULT_USER) }}" alt=""/>
                                            @endif
                                            <a href="#" class="user-link">{{ $val->full_name }}</a>
                                            <span class="user-subhead">
                                                @if($val->user_type == 1)
                                                    Admin
                                                @elseif($val->user_type == 2)
                                                    Account
                                                @else
                                                    Staff
                                                @endif
                                            </span>
                                        </td>
                                        <td>{{ $val->user_name }}</td>
                                        <td>
                                            @if($val->user_type == 1)
                                                Admin
                                               @elseif($val->user_type == 2)
                                                Account
                                            @else
                                                Staff
                                            @endif </td>

                                        <td>
                                            @if(is_null($val->last_login_at))
                                                Not Logged In
                                            @else
                                                {{ \Carbon\Carbon::parse($val->last_login_at)->diffForHumans() }}
                                            @endif
                                        </td>


                                        <td style="width: 20%;">
                                            <a href="{{ route('staff.view', $val->id) }}" class="table-link" title="View details">
                                        <span class="fa-stack">
                                            <i class="fa fa-square fa-stack-2x" ></i>
                                            <i class="fa fa-search-plus fa-stack-1x fa-inverse"></i>
                                        </span>
                                            </a>
                                            <a href="{{route('staff.edit',$val->id)}}" class="table-link" title="Edit">
                                        <span class="fa-stack">
                                            <i class="fa fa-square fa-stack-2x"></i>
                                            <i class="fa fa-pencil fa-stack-1x fa-inverse"></i>
                                        </span>
                                            </a>
                                            @if ($val->id == Auth::user()->id)
                                            @else
                                                <a  href="#deleteStaff" data-key="" class="table-link danger delete" title="Delete" data-ids="{{ $val->id }}" data-toggle="modal" data-rel="delete" data-user="{{$val->full_name}}">
                                                    <span class="fa-stack">
                                                        <i class="fa fa-square fa-stack-2x"></i>
                                                        <i class="fa fa-trash-o fa-stack-1x fa-inverse"></i>
                                                    </span>
                                                </a>

                                            @endif
                                        </td>
                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>

                        {{--<div>
                            <strong>Showing {{ $assigned->firstItem() }} to {{ $assigned->lastitem() }} of {{ $assigned->total() }} entries </strong>
                        </div>--}}
                        <p>Showing {{$staff->currentPage()}} to {{$staff->perPage()}}  of {{$staff->total()}} entries </p>

                        <div align="right">

                            {{ $staff->links() }}
                        </div>

                    </div>



                </div>
            </div>
        </div>
    </div>
    @include('pages.staff.modal')

@endsection

@section('script')
    <script>
        $('#deleteStaff').on('show.bs.modal', function (e) {
            //e.preventDefault();
            var button = $(e.relatedTarget);
            var ids = button.data('ids');
            var user = button.data('user');

            // Pass form reference to modal for submission on yes/ok
            var form = $(e.relatedTarget).closest('form');
            $(this).find('.modalfooter #confirm').data('form', form);
            $("#hidden_id").val(ids);
            $(".hidden_title").html(' "' + user + '" ');
        });


        $('#deleteStaff').find('#confirm_yes').on('click', function () {

            //set csrf token
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            //fetching id
            var id = $("#hidden_id").val();

            $.ajax({
                type: "POST",
                url: "{{route('staff.delete')  }}",
                headers: {
                    'XCSRFToken': $('meta[name="csrf-token"]').attr('content')
                },

                data: "id=" + id,
                success: function (msg) {
                    console.log(msg);
                    // alert(msg.error);
                    if(msg.error == false){
                        $("#deleteStaff").modal("hide");
                        $('#showMessage').find('.success').show();
                        $("#showMessage").modal("show");
                    }
                    else
                    {
                        $("#deleteStaff").modal("hide");
                        $('#showMessage').find('.error').show();
                        $("#showMessage").modal("show");
                    }
                    // window.location.reload();
                }
            });
        });

        $('#show_message').on('click', function () {
            window.location.reload();
        });
    </script>
@endsection

resources/views/pages/staff/view.blade.php
@extends('layouts.app')

@section('content')
		<br>
	
<div class="container">
  <div class="col-lg-6-offset-4">
 	 <div class="col-lg-6">
  	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h3 class="panel-title">Staff Details</h3>
	  </div>
	  <div class="panel-body">
	   
	    	
	    	<strong>Full Name : </strong>{{ $staff->full_name }}
	    	<hr>
	    	<strong>Contact Number : </strong>{{ $staff->contact }}
	    	<hr>
	    	<strong>Joined Date : </strong>{{ $staff->join_date }}
	    	<hr>
	    	<strong>Department : </strong>{{ $staff->department }}
	    	<hr>
	    	<strong>User Name : </strong>{{ $staff->user_name }}
	    	<hr>
            <strong>Permanent Address : </strong>{{ $staff->permanent_address }}
            <hr>
            <strong>Temporary Address : </strong>{{ $staff->temporary_address }}
            <hr>
            <strong>Social Media link </strong>  <div class="col-md-12"> 
                    <ul class="social-network social-circle">
                       @if (isset($staff->facebook_link))
                            <li><a href="{{ $staff->facebook_link }}" target="_self" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                       @endif
                        @if (isset($staff->twitter_link))
                            <li><a href="#" target="_self" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                        @endif
                        @if (isset($staff->google_link))
                            <li><a href="google.com" target="_blank" class="icoGoogle" title="Google +"><i class="fa fa-google-plus"></i></a></li>
                        @endif
                        @if (isset($staff->linkedin_link))
                            <li><a href="linkedin.com" target="_blank" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                        @endif
                    </ul>               
                </div>
            <hr>
		    	
	    
	    </div>
	    </div>
	    </div>
	    <div class="col-lg-6">
                
                 <div class="media">
                        <div align="center">
                            <img class="thumbnail img-responsive"
                                 @if($staff->profile_image == null)
                                 src="{{ asset(STATIC_DIR.'images/default.jpg') }}"
                                 @else
                                 src="{{ asset(STATIC_DIR.'storage/'.$staff->profile_image) }}"
                                 @endif
                                 width="300px" height="300px"
                            >
                        </div>
                       
                    </div>

	    </div>

	    @if (Auth::user()->isAdmin()==1)

	    <div class="col-lg-12">
                         <div class="col-lg-12">
                        <h2>Task Assigned to {{ $staff->full_name }}</h2>
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th>Task ID</th>
                                        <th>Title</th>
                                        <th>Created At</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach($assigned as $data)
                                    <tr>
                                        <td>{{ $data->id }}</td>
                                        <td>{{ $data->name }}</td>
                                        <td>{{ $data->created_at }}</td>
                                         <td class="center">
                                            @if($data->status==0)
                                                <p class="list-group-item-text">
                                                  <span class="label label-success">New</span>
                                                </p>
                                            @elseif($data->status==1)
                                                <p class="list-group-item-text">
                                                  <span class="label label-success">Opened</span>
                                                </p>
                                            @elseif($data->status==2)
                                                <p class="list-group-item-text">
                                                  <span class="label label-danger">Pending</span>
                                                </p>
                                            @elseif($data->status==3)
                                                <p class="list-group-item-text">
                                                  <span class="label label-success">Completed</span>
                                                </p>
                                            @endif
                                        </td>
                                        <td>
                                            <a href="{{ route('task.view',$data->id) }}" class="btn btn-default">View</a>
                                            <a href="{{ route('task.edit',$data->id) }}" class="btn btn-default">Edit</a>
                                           {{--   <form action="{{ route('task.delete',$data->id) }}" method="post">
                                             {{ csrf_field() }}
                                                    <button onclick="myFunction()" class="btn btn-danger btn-block">Delete</button>
                                             
                                            </form> --}}
                                            {{--<a href="{{ route('task.delete',$data->id) }}" class="btn btn-default">Delete </a>--}}
                                        </td>
                                    </tr>
                                @endforeach

                                </tbody>
                            </table>
                         
                            <div>
                            	<strong>Showing {{ $assigned->firstItem() }} to {{ $assigned->lastitem() }} of {{ $assigned->total() }} entries </strong>
                            </div>
                            <div align="center">
                            	 {{ $assigned->links() }}
                            </div>
                      
                        </div>
                    </div>
                    </div>
                    @endif

	  </div>
	</div>

@endsection