routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
if(!defined('STATIC_DIR')) define("STATIC_DIR","public/");
if(!defined('DEFAULT_USER')) define('DEFAULT_USER','public/icon/default-user-1.png');

//redirecting to home
Route::get('/',['middleware' => 'auth', 'uses' => 'HomeController@index']);
Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();
/**
 * Staff management
 */
Route::group(['prefix' => 'staff','as'=>'staff.'], function () {
    Route::get('/',['uses' => 'Auth\RegisterController@show','as' => 'show']);
    Route::get('/edit/{id}', ['uses' => 'Auth\RegisterController@getEdit','as' => 'edit']);
    Route::post('/edit/{id}', ['uses' => 'Auth\RegisterController@update']);
    Route::get('/view/{id}', ['uses' => 'Auth\RegisterController@getView','as' => 'view']);
    Route::post('/delete', ['uses' => 'Auth\RegisterController@delete','as' => 'delete']);
    Route::get('/role', ['uses' => 'Auth\RegisterController@editRole','as' => 'role']);
    Route::post('/role', ['uses' => 'Auth\RegisterController@updateRole']);
});

Route::get('/profile/view/{id}', ['uses' => 'ProfileController@view','as' => 'profile.view']);
Route::get('/password/edit', ['uses' => 'ProfileController@editPassword','as' => 'password.edit']);
Route::post('password/edit/{id}', ['uses' => 'ProfileController@updatePassword','as' => 'password.update']);

/**
 *  Department
 */
Route::group(['prefix' => 'department','as'=>'department.'], function () {
    Route::get('/index', ['uses' => 'DepartmentController@getIndex','as' => 'home']);
    Route::get('/', ['uses' => 'DepartmentController@create','as' => 'create']);
    Route::post('/', ['uses' => 'DepartmentController@store','as' => 'create']);
    Route::get('/edit/{id}', ['uses' => 'DepartmentController@edit','as' => 'edit']);
    Route::post('/edit/{id}', ['uses' => 'DepartmentController@update']);
});

/**
 *  Task management
 */
Route::group(['prefix' => 'task','as'=>'task.'], function () {
    Route::get('/create', ['uses' => 'TaskController@create','as' => 'create'])->middleware(['auth','admin']);
    Route::post('/create', ['uses' => 'TaskController@store','as' => 'store'])->middleware(['auth','admin']);
    Route::get('/show', ['uses' => 'TaskController@show','as' => 'show'])->middleware(['auth']);
    Route::get('/completed', ['uses' => 'TaskController@showCompletedTask','as' => 'show_completed_task'])->middleware(['auth']);

    Route::get('/assign', ['uses' => 'TaskController@getAssign','as' => 'assign'])->middleware(['auth','admin']);
    Route::post('/assign', ['uses' => 'TaskController@assign','as' => 'assign'])->middleware(['auth','admin']);
    Route::get('/assign/id', ['uses' => 'TaskController@getAssignedUserById','as' => 'getUserByTaskId'])->middleware(['auth','admin']);


    Route::get('/view/{id}',['uses' => 'TaskController@viewTask','as' => 'view']);
    Route::get('/status/{id}', ['uses' => 'TaskController@status','as' => 'status']);
    Route::get('/edit/{id}', ['uses' => 'TaskController@edit','as' => 'edit'])->middleware(['auth','admin']);
    Route::post('/edit/{id}', ['uses' => 'TaskController@update'])->middleware(['auth','admin']);
    Route::post('/delete', ['uses' => 'TaskController@delete','as' => 'delete'])->middleware(['auth','admin']);

    //change task status plus add remarks.
    Route::post('/remarks/store', ['uses' => 'TaskController@addRemarks', 'as' => 'store_remarks'])->middleware(['auth']);

    //get task  from usre id
    Route::get('/user/task',['uses' => 'TaskController@getTaskByUserId', 'as' => 'user-task']);

    //client routes
    Route::get('/client/show',['uses' => 'TaskController@getAllClient', 'as' => 'client-retrieve'])->middleware(['auth','admin']);
    Route::post('/client/add', ['uses' => 'TaskController@storeClient','as' => 'client-store'])->middleware(['auth','admin']);
    Route::post('/client/delete', ['uses' => 'TaskController@deleteClient','as' => 'client-delete'])->middleware(['auth','admin']);

    Route::post('/client/retrieve/clientinfo',['uses' => 'TaskController@getClientById', 'as' => 'client-retrieve-id'])->middleware(['auth','admin']);
    Route::post('/client/edit', ['uses' => 'TaskController@editClient','as' => 'client-edit'])->middleware(['auth','admin']);



});


/**
 *  Search
 */
Route::post('/result', ['uses' => 'SearchController@getResult','as' => 'search.result']);

Route::get('/list', ['uses' => 'SearchController@list']);

/**
 * Comment
 */
Route::post('/comment/{taskId}', ['uses' => 'CommentController@store','as' => 'comment']);

Route::get('/comment/delete/{id}', ['uses' => 'CommentController@delete','as' => 'comment.delete']);

Route::get('/comment/update/{id}', ['uses' => 'CommentController@edit','as' => 'comment.update']);

Route::post('/comment/update/{id}', ['uses' => 'CommentController@update','as' => 'comment.update']);



/**
 * Telephone Directory
 */
Route::group(['prefix' => 'telephone','as' => 'telephone.'],function(){
   Route::get('/',['uses' => 'TelephoneController@index', 'as' => 'index']);
   Route::get('/register',['uses' => 'TelephoneController@registerTelephone', 'as' => 'register_telephone']);
   Route::post('/register',['uses' => 'TelephoneController@postRegisterTelephone', 'as' => 'register_telephone']);

   //edit telephone
    Route::get('/edit/{id}',['uses' => 'TelephoneController@editTelephone', 'as' => 'edit_telephone']);
    Route::post('/update',['uses' => 'TelephoneController@postEditTelephone', 'as' => 'update_telephone']);

    //delete telephone information
    Route::post('/delete',['uses' => 'TelephoneController@deleteTelephone', 'as' => 'delete_telephone']);


});

/**
 * Application Leave
 */
Route::group(['prefix' => 'leave','as' => 'leave.'],function(){
   Route::get('/',['uses' => 'LeaveController@index', 'as' => 'list']);
   Route::get('/application/fill',['uses' => 'LeaveController@registerLeave', 'as' => 'register_leave']);
   Route::post('/register',['uses' => 'LeaveController@postRegisterLeave', 'as' => 'store_leave']);

   //edit telephone
    Route::get('/edit/{id}',['uses' => 'LeaveController@editTelephone', 'as' => 'edit_telephone']);
    Route::post('/update',['uses' => 'LeaveController@postEditTelephone', 'as' => 'update_telephone']);

    //delete telephone information
    Route::post('/delete',['uses' => 'LeaveController@deleteTelephone', 'as' => 'delete_telephone']);


});

resources/views/layouts/partials/_footer.blade.php
<!-- BEGIN FOOTER -->
<div class="page-footer" style="background-color: #c5c5c5;margin-bottom:0px;">
    <div class="page-footer-inner col-md-12 text-center">
        <p><?= date('Y') ?> &copy; Task Management System developed by <strong><a href="http://ramlaxmangroup.com/">Technology Sales Pvt. Ltd.</a></strong></p>
    </div>
    <div class="scroll-to-top">
        <i class="icon-arrow-up"></i>
    </div>
</div>
<!-- END FOOTER -->
<script src="{{ asset('public/assets/global/plugins/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('public/metisMenu/metisMenu.min.js') }}"></script>
<script src="{{ asset('public/dist/js/sb-admin-2.js') }}"></script>
<script src="{{ asset(STATIC_DIR.'assets/global/plugins/jquery-ui/jquery-ui.min.js') }}"></script><script src="{{ asset('public/assets/global/plugins/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset(STATIC_DIR.'assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js')}}" type="text/javascript"></script>
<script src="{{ asset(STATIC_DIR.'assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js')}}" type="text/javascript"></script>
<script src="{{ asset(STATIC_DIR.'assets/global/plugins/jquery.blockui.min.js')}}" type="text/javascript"></script>
<script src="{{ asset(STATIC_DIR.'assets/global/plugins/uniform/jquery.uniform.min.js')}}" type="text/javascript"></script>
<script src="{{ asset(STATIC_DIR.'assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js')}}" type="text/javascript"></script>
<script type="text/javascript" src="{{ asset(STATIC_DIR.'assets/global/plugins/datatables/media/js/jquery.dataTables.min.js') }}"></script>

@yield('script')
<script>



</script>
</body>

</html>

resources/views/layouts/partials/_head.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf-token" content="{{ csrf_token() }}" />

    <title>Task Management - @yield('page-title')</title>
    <link rel="icon" href="{!! asset('/public/icon/tech.gif') !!}"/>
    <link href="{{ asset('public/assets/global/plugins/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('public/dist/css/sb-admin-2.css') }}" rel="stylesheet">
    <link href="{{ asset('public/css/custom.css') }}" rel="stylesheet">

    <link href="{{ asset('public/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />

    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,600,700,300|Titillium+Web:200,300,400" rel="stylesheet" type="text/css"/>
    <link href="{{ asset(STATIC_DIR.'assets/global/plugins/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{ asset(STATIC_DIR.'assets/global/plugins/simple-line-icons/simple-line-icons.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{ asset(STATIC_DIR.'assets/global/plugins/uniform/css/uniform.default.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{ asset(STATIC_DIR.'assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{ asset(STATIC_DIR.'assets/global/css/components.css')}}" id="style_components" rel="stylesheet" type="text/css"/>
    <link href="{{ asset(STATIC_DIR.'assets/admin/layout/css/layout.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{ asset(STATIC_DIR.'assets/admin/layout/css/custom.css')}}" rel="stylesheet" type="text/css"/>
    <link rel="stylesheet" href="{{ asset(STATIC_DIR.'assets/global/plugins/datatables/media/css/jquery.dataTables.min.css') }}">
    
    <style>
        .sidebar {
            z-index: 1;
            position: absolute;
            width: 235px;
            margin-top: 51px;
        }
        .page-content-wrapper .page-content {
	        margin-left: 235px;
	        margin-top: 0px;
	        min-height: 90vh;
	        /*padding: 25px 20px 10px 20px;*/
        }
        .white-box {
	        margin-top: auto;
	        margin-left: auto;
	        margin-right: auto;
	        margin-bottom: 10px;
	        background: rgba(255,255,255,0.9);
	        padding-left: 20px;
	        padding-right: 20px;
	        padding-top: 20px;
	        padding-bottom: 0px;
	        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,0.15);
	        -moz-box-shadow: 0 1px 2px rgba(0,0,0,0.15);
	        box-shadow: 0 1px 2px rgba(0,0,0,0.15);
	        -webkit-border-radius: 5px;
	        -moz-border-radius: 5px;
	        -ms-border-radius: 5px;
	        -o-border-radius: 5px;
	        border-radius: 5px;
	        /*border: 1px solid #23282c;*/
        }
        .white-box-title {
	        margin-left: auto;
	        margin-right: auto;
	        background: rgba(255,255,255,0.9);
	        /*padding: 15px 10px 0px 10px;*/
	        padding-left: 20px;
	        padding-right: 20px;
	        padding-top: 20px;
	        padding-bottom: 0px;
	        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,0.15);
	        -moz-box-shadow: 0 1px 2px rgba(0,0,0,0.15);
	        box-shadow: 0 1px 2px rgba(0,0,0,0.15);
	        -webkit-border-radius: 5px;
	        -moz-border-radius: 5px;
	        -ms-border-radius: 5px;
	        -o-border-radius: 5px;
	        border-radius: 5px;
	        /*border: 1px solid #23282c;*/
        }
        .page-content{
	        background-color: #f4f5f4 !important;
        }
	    .form-actions{
		    padding-bottom: 20px;
	    }
    </style>
    @yield('css')

</head>

resources/views/layouts/partials/_nav.blade.php
<ul class="nav navbar-top-links navbar-right">

    <!-- /.dropdown -->
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
            <li><a href="{{ route('profile.view',Auth::user()->id) }}"><i class="fa fa-user fa-fw"></i> My Profile</a>
            </li>
            {{--<li><a href="{{ route('staff.edit', Auth::user()->id) }}"><i class="fa fa-gear fa-fw"></i> Settings</a>--}}
            {{--</li>--}}
            {{--<li class="divider"></li>--}}
            <li>
                <a href="{{ route('logout') }}" onclick="event.preventDefault();
                                document.getElementById('logout-form').submit();">
                    <i class="fa fa-power-off"></i>  Logout
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
            </li>
        </ul>
        <!-- /.dropdown-user -->
    </li>
    <!-- /.dropdown -->
</ul>

resources/views/layouts/partials/_sidebar.blade.php
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search">

                {{-- profile prefiew --}}
                <div class="row"  >
                    <div class="profile-header-container">
                        <img id="profile image"  @if(Auth::user()->profile_image == null)
                                                        src="{{asset(STATIC_DIR.'images/default.jpg')}} "
                                                 @else
                                                         src="{{asset(STATIC_DIR.'storage/'.Auth::user()->profile_image)}}"
                                                @endif
                             style="max-height: 90px; max-width: 150px"   />

                        <!-- badge -->
                        <div class="rank-label-container">
                            <span class="label label-default rank-label">{{ Auth::user()->full_name }}</span>
                        </div>
                    </div>
                </div>
                {{-- end profile preview --}}

            </li>

            <li>
                <a href="{{ route('home') }}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>

            @if (Auth::user()->isAdmin()==1)

            <li>
                <a href="{{ route('profile.view',Auth::user()->id) }}"><i class="glyphicon glyphicon-user"></i> My profile</a>
            </li>

                <li>
                    <a href="#"><i class="glyphicon glyphicon-user"></i> Staff management <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="{{ route('register') }}">
                                <i class="fa fa-plus"></i>Register Staff
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('staff.show') }}">
                                <i class="fa fa-list"></i> View Staff</a>
                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
            @endif

            @if (Auth::user()->user_type==1)
            <li>
                <a href="#"><i class="glyphicon glyphicon-tasks"></i> Task Management<span class="fa arrow"></span></a>

                <ul class="nav nav-second-level">

                    <li>
                        <a href="{{ route('task.client-retrieve') }}"><i class="glyphicon glyphicon-user"></i> Clients</a>
                    </li>

                    <li>
                        <a href="{{ route('task.create') }}"><i class="glyphicon glyphicon-pencil"></i> Create new task</a>
                    </li>

                    <li>
                        <a href="{{ route('task.show') }}"><i class="glyphicon glyphicon-eye-open"></i> View all task</a>
                    </li>

                    <li>
                        <a href="{{ route('task.assign') }}"><i class="glyphicon glyphicon-share"></i> Assign task</a>
                    </li>

                    <li>
                        <a href="{{ route('task.show_completed_task') }}"><i class="glyphicon glyphicon-check"></i> Completed task</a>
                    </li>

                </ul>
            </li>
            @endif

            @if(Auth::user()->user_type == 1)
                <li>
                    <a href="#"><i class="glyphicon glyphicon-phone-alt"></i> Telephone Directory<span class="fa arrow"></span></a>

                    <ul class="nav nav-second-level">
                        <li>
                            <a href="{{ route('telephone.register_telephone') }}"><i class="glyphicon glyphicon-pencil"></i> Create New Telephone</a>
                        </li>

                        @endif

                        <li>
                            <a href="{{route('telephone.index')}}"><i class="	glyphicon glyphicon-earphone"></i> Show Telephone List</a>
                        </li>

                    </ul>
                </li>

                @if (Auth::user()->user_type==1)
                    <li>
                        <a href="#"><i class="glyphicon glyphicon-tasks"></i> Leave Management<span class="fa arrow"></span></a>

                        <ul class="nav nav-second-level">
                            <li>
                                <a href="{{ route('leave.register_leave') }}"><i class="glyphicon glyphicon-pencil"></i> Permission Form</a>
                            </li>

                            <li>
                                <a href="{{ route('leave.list') }}"><i class="glyphicon glyphicon-eye-open"></i> View all Leave</a>
                            </li>

                        </ul>
                    </li>
                @endif


            {{--<li>
                <a href="{{ route('home') }}"><i class="glyphicon glyphicon-cog"></i> Service & Maintenance Form</a>
            </li>--}}



                {{--<li>
                    <a href="#"><i class="glyphicon glyphicon-open-file"></i> Upload Files</a>
                </li>--}}

                {{--<li>
                    <a href="{{ route('staff.role') }}"><i class="fa fa-edit fa-fw"></i> Change staff role</a>
                </li>--}}

                {{--<li>
                    <a href="#"><i class="fa fa-wrench fa-fw"></i> Department <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="{{ route('department.home') }}"> View department</a>
                        </li>
                        <li>
                            <a href="{{ route('department.create') }}"> Add department</a>
                        </li>

                    </ul>
                    <!-- /.nav-second-level -->
                </li>--}}
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>