routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
if(!defined('STATIC_DIR')) define("STATIC_DIR","public/");
if(!defined('DEFAULT_USER')) define('DEFAULT_USER','public/icon/default-user-1.png');

//redirecting to home
Route::get('/',['middleware' => 'auth', 'uses' => 'HomeController@index']);
Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();
/**
 * Staff management
 */
Route::group(['prefix' => 'staff','as'=>'staff.'], function () {
    Route::get('/',['uses' => 'Auth\RegisterController@show','as' => 'show']);
    Route::get('/edit/{id}', ['uses' => 'Auth\RegisterController@getEdit','as' => 'edit']);
    Route::post('/edit/{id}', ['uses' => 'Auth\RegisterController@update']);
    Route::get('/view/{id}', ['uses' => 'Auth\RegisterController@getView','as' => 'view']);
    Route::post('/delete', ['uses' => 'Auth\RegisterController@delete','as' => 'delete']);
    Route::get('/role', ['uses' => 'Auth\RegisterController@editRole','as' => 'role']);
    Route::post('/role', ['uses' => 'Auth\RegisterController@updateRole']);
});

Route::get('/profile/view/{id}', ['uses' => 'ProfileController@view','as' => 'profile.view']);
Route::get('/password/edit', ['uses' => 'ProfileController@editPassword','as' => 'password.edit']);
Route::post('password/edit/{id}', ['uses' => 'ProfileController@updatePassword','as' => 'password.update']);

/**
 *  Department
 */
Route::group(['prefix' => 'department','as'=>'department.'], function () {
    Route::get('/index', ['uses' => 'DepartmentController@getIndex','as' => 'home']);
    Route::get('/', ['uses' => 'DepartmentController@create','as' => 'create']);
    Route::post('/', ['uses' => 'DepartmentController@store','as' => 'create']);
    Route::get('/edit/{id}', ['uses' => 'DepartmentController@edit','as' => 'edit']);
    Route::post('/edit/{id}', ['uses' => 'DepartmentController@update']);
});

/**
 *  Task management
 */
Route::group(['prefix' => 'task','as'=>'task.'], function () {
    Route::get('/create', ['uses' => 'TaskController@create','as' => 'create'])->middleware(['auth','admin']);
    Route::post('/create', ['uses' => 'TaskController@store','as' => 'store'])->middleware(['auth','admin']);
    Route::get('/show', ['uses' => 'TaskController@show','as' => 'show'])->middleware(['auth']);
    Route::get('/completed', ['uses' => 'TaskController@showCompletedTask','as' => 'show_completed_task'])->middleware(['auth']);

    Route::get('/assign', ['uses' => 'TaskController@getAssign','as' => 'assign'])->middleware(['auth','admin']);
    Route::post('/assign', ['uses' => 'TaskController@assign','as' => 'assign'])->middleware(['auth','admin']);
    Route::get('/assign/id', ['uses' => 'TaskController@getAssignedUserById','as' => 'getUserByTaskId'])->middleware(['auth','admin']);


    Route::get('/view/{id}',['uses' => 'TaskController@viewTask','as' => 'view']);
    Route::get('/status/{id}', ['uses' => 'TaskController@status','as' => 'status']);
    Route::get('/edit/{id}', ['uses' => 'TaskController@edit','as' => 'edit'])->middleware(['auth','admin']);
    Route::post('/edit/{id}', ['uses' => 'TaskController@update'])->middleware(['auth','admin']);
    Route::post('/delete', ['uses' => 'TaskController@delete','as' => 'delete'])->middleware(['auth','admin']);

    //change task status plus add remarks.
    Route::post('/remarks/store', ['uses' => 'TaskController@addRemarks', 'as' => 'store_remarks'])->middleware(['auth']);

    //get task  from usre id
    Route::get('/user/task',['uses' => 'TaskController@getTaskByUserId', 'as' => 'user-task']);

    //client routes
    Route::get('/client/show',['uses' => 'TaskController@getAllClient', 'as' => 'client-retrieve'])->middleware(['auth','admin']);
    Route::post('/client/add', ['uses' => 'TaskController@storeClient','as' => 'client-store'])->middleware(['auth','admin']);
    Route::post('/client/delete', ['uses' => 'TaskController@deleteClient','as' => 'client-delete'])->middleware(['auth','admin']);

    Route::post('/client/retrieve/clientinfo',['uses' => 'TaskController@getClientById', 'as' => 'client-retrieve-id'])->middleware(['auth','admin']);
    Route::post('/client/edit', ['uses' => 'TaskController@editClient','as' => 'client-edit'])->middleware(['auth','admin']);



});


/**
 *  Search
 */
Route::post('/result', ['uses' => 'SearchController@getResult','as' => 'search.result']);

Route::get('/list', ['uses' => 'SearchController@list']);

/**
 * Comment
 */
Route::post('/comment/{taskId}', ['uses' => 'CommentController@store','as' => 'comment']);

Route::get('/comment/delete/{id}', ['uses' => 'CommentController@delete','as' => 'comment.delete']);

Route::get('/comment/update/{id}', ['uses' => 'CommentController@edit','as' => 'comment.update']);

Route::post('/comment/update/{id}', ['uses' => 'CommentController@update','as' => 'comment.update']);



/**
 * Telephone Directory
 */
Route::group(['prefix' => 'telephone','as' => 'telephone.'],function(){
   Route::get('/',['uses' => 'TelephoneController@index', 'as' => 'index']);
   Route::get('/register',['uses' => 'TelephoneController@registerTelephone', 'as' => 'register_telephone']);
   Route::post('/register',['uses' => 'TelephoneController@postRegisterTelephone', 'as' => 'register_telephone']);

   //edit telephone
    Route::get('/edit/{id}',['uses' => 'TelephoneController@editTelephone', 'as' => 'edit_telephone']);
    Route::post('/update',['uses' => 'TelephoneController@postEditTelephone', 'as' => 'update_telephone']);

    //delete telephone information
    Route::post('/delete',['uses' => 'TelephoneController@deleteTelephone', 'as' => 'delete_telephone']);


});

/**
 * Application Leave
 */
Route::group(['prefix' => 'leave','as' => 'leave.'],function(){
   Route::get('/',['uses' => 'LeaveController@index', 'as' => 'list']);
   Route::get('/application/fill',['uses' => 'LeaveController@registerLeave', 'as' => 'register_leave']);
   Route::post('/register',['uses' => 'LeaveController@postRegisterLeave', 'as' => 'store_leave']);

   //edit telephone
    Route::get('/edit/{id}',['uses' => 'LeaveController@editTelephone', 'as' => 'edit_telephone']);
    Route::post('/update',['uses' => 'LeaveController@postEditTelephone', 'as' => 'update_telephone']);

    //delete telephone information
    Route::post('/delete',['uses' => 'LeaveController@deleteTelephone', 'as' => 'delete_telephone']);


});

app/Telephone.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Telephone extends Model
{
    protected  $table = 'telephones';
}

app/Http/Controllers/Api/TelephoneController.php
<?php

namespace App\Http\Controllers\Api;

use App\Helper\Tools;
use App\Telephone;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TelephoneController extends Controller
{
    public function showAllTelephoneDirectory(){
        $telephone = Telephone::all();

        $responseData = Tools::setResponse('success','Telephone Listing Successfull', $telephone,'');
        $status = 200;
        return response()->json($responseData,$status);


    }
}

app/Http/Controllers/TelephoneController.php
<?php

namespace App\Http\Controllers;

use App\Helper\Tools;
use App\Telephone;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class TelephoneController extends Controller
{
    public function index(){
        $data['telephone'] = Telephone::all();
//        dd($data);
        return view('pages.telephone.index',$data);
    }

    public function registerTelephone(){
        return view("pages.telephone.register_telephone");
    }

    public function postRegisterTelephone(Request $request){
        $this->validate($request,[
           'name' => 'required|max:50',
           'department' => 'required|max:50',
           'post' => 'required|max:50',
           'contact' => 'required|digits_between:5,12',
//           'ext_number' => 'required|max:5'

        ]);

        if(isset($request->ext_number)){
            $this->validate($request,[
                'ext_number' => 'required|digits_between:3,5',
            ]);

        }

        $telephone = new Telephone();
        $telephone->name = $request->name;
        $telephone->department = $request->department;

        $telephone->post = $request->post;
        $telephone->contact = $request->contact;

        $telephone->ext_number = $request->ext_number;
        $telephone->created_at = date('Y-m-d H:i:s');

        if(isset($request->staff_image)){
            $telephone->staff_image = $request->file('staff_image')->store('files/staff_image','public');

        }
        $telephone->save();



        \Session::flash('success', 'New Telephone Directory Registered Successfully');
        return redirect()->route('telephone.index');
    }

    //get edit form
    public function editTelephone($id){
        $data['telephone'] = Telephone::find($id);
        return view ('pages.telephone.edit_telepohone',$data);
    }

    //edit in model here
    public function postEditTelephone(Request $request){
        $this->validate($request,[
            'name' => 'required|max:50',
            'department' => 'required|max:50',
            'post' => 'required|max:50',
            'contact' => 'required|digits_between:5,12',
//           'ext_number' => 'required|max:5'

        ]);

        if(isset($request->ext_number)){
            $this->validate($request,[
                'ext_number' => 'required|digits_between:3,5',
            ]);

        }


        $telephone = Telephone::find($request->telephone_id);
        $telephone->name = $request->name;
        $telephone->department = $request->department;

        $telephone->post = $request->post;
        $telephone->contact = $request->contact;

        $telephone->ext_number = $request->ext_number;
        $telephone->created_at = date('Y-m-d H:i:s');

        if(isset($request->staff_image)){
            \Storage::delete('public/'.$telephone->staff_image);
            $telephone->staff_image = $request->file('staff_image')->store('files/staff_image','public');

        }
        $telephone->save();

        \Session::flash('success', 'Telephone Directory Updated Successfully');
        return redirect()->route('telephone.index');
    }

    //ajax delete request
    public function deleteTelephone(Request $request){

        $validator = Validator::make($request->all(), [
            'id' => 'required',
        ]);

        if ($validator->fails()) {
            $responseData = Tools::setResponse('fail', 'Missing Parameter', '', '');
            $status = 422;

            return response()->json($responseData,$status);
        }

        //deleting group permission also
        $telephone = Telephone::where('id',$request->id)->first();
        $telephone->delete();

//        \Session::flash('success','User Deleted Successfully');
        $responseData = Tools::setResponse('success', 'Telephone Deleted Successfully', '', '');
        return response($responseData,200);
    }
}

resources/views/pages/telephone/edit_telepohone.blade.php
@extends('layouts.app')
@section('page-title')
    Register New Telephone
@stop
@section('css')
    <link rel="stylesheet" href="{{ asset(STATIC_DIR.'css/jquery.dataTables.min.css') }}">
    <link href="{{ asset(STATIC_DIR.'css/style.css')}}" rel="stylesheet" type="text/css"/>
@stop

@section('content')
    <div class="white-box">
        <div class="row">
            <div class="col-md-8">
                <h2>Edit Employee Telephone Registration</h2>

                <form action="{{route('telephone.update_telephone')}}" method="POST" enctype="multipart/form-data">
                    <input type="hidden" name="telephone_id" value="{{$telephone->id}}">
                    @csrf
                    <div class="form-group">
                        <label for="" class="control-label" >Name <span style="color: red;">*</span></label>
                        <input type="text" class="form-control" name="name" placeholder="Enter Employee Name" required value="{{old('name') ?? $telephone->name}}" >
                        @if($errors->has('name'))
                            <span class="help-block" style="color:red;">
                                 {{$errors->first('name')}}
                            </span>
                        @endif

                    </div>

                    <div class="form-group">
                        <label for="" class="control-label">Department: <span style="color: red;">*</span></label>
                        <select name="department" class="form-control" id="exampleFormControlSelect1" required>
                            <option disabled="">Select One Department</option>
                            <option value="Software" {{ ( (old('department')  ?? $telephone->department) == 'Software') ? "selected" : '' }}>Software </option>
                            <option value="Marketing" {{ ( (old('department') ?? $telephone->department) == 'Marketing') ? "selected" : '' }}>Marketing</option>
                            <option value="Human Resource" {{ (  (old('department') ?? $telephone->department) == 'Human Resource') ? "selected" : '' }}>Human Resource </option>
                            <option value="Account" {{ ( (old('department')?? $telephone->department) == 'Account') ? "selected" : '' }}>Account</option>
                            <option value="Administration" {{ (  (old('department') ?? $telephone->department) == 'Administration') ? "selected" : '' }}>Administration </option>
                            <option value="Hardware" {{ (  (old('department') ?? $telephone->department) == 'Hardware') ? "selected" : '' }}>Hardware </option>
                        </select>

                        @if($errors->has('department'))
                            <span class="help-block" style="color:red;">
                                 {{$errors->first('department')}}
                            </span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label for="" class="control-label" >Post <span style="color: red;">*</span></label>
                        <input type="text" class="form-control" name="post"  placeholder="Enter Employee Post" required value="{{old('post') ?? $telephone->post}}">
                        @if($errors->has('post'))
                            <span class="help-block" style="color:red;">
                                 {{$errors->first('post')}}
                            </span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label for=""  class="control-label">Contact Number <span style="color: red;">*</span></label>
                        <input type="number" class="form-control" name="contact" min="0" placeholder="Enter Contact Number" required value="{{old('contact') ?? $telephone->contact}}">
                        @if($errors->has('contact'))
                            <span class="help-block" style="color:red;">
                                 {{$errors->first('contact')}}
                            </span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label for="" class="control-label">Extension Number</label>
                        <input type="number" class="form-control" name="ext_number" min="0" placeholder="Enter Extension Number" value="{{old('ext_number') ?? $telephone->ext_number}}">
                        @if($errors->has('ext_number'))
                            <span class="help-block" style="color:red;">
                                 {{$errors->first('ext_number')}}
                            </span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label for="" class="control-label">Staff Image</label>
                        <div>
                            @if($telephone->staff_image != null)
                                <img src="{{ asset(STATIC_DIR.'storage/'.$telephone->staff_image) }}" class="img img-responsive" style="max-height:100px; max-width:100px;" alt="">
                                <br>
                            @endif
                        </div>
                        <input type="file" class="" name="staff_image">
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">
                            <i class="fa fa-edit"></i> Edit
                        </button>
                    </div>

                </form>
            </div>


        </div>
    </div>
@endsection

@section('script')
@endsection

resources/views/pages/telephone/index.blade.php
@extends('layouts.app')
@section('page-title')
    Task Listing
@stop
@section('css')
    <link rel="stylesheet" href="{{ asset(STATIC_DIR.'css/jquery.dataTables.min.css') }}">
    <link href="{{ asset(STATIC_DIR.'css/style.css')}}" rel="stylesheet" type="text/css"/>
@stop

@section('content')
    <div class="white-box">
        <div class="row" >
            <div class="col-lg-12 col-md-12">
                <div class="main-box clearfix">
                    <div class="table-responsive" >
                        <table class="table table-striped table-bordered" id="myTable">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Department</th>
                                    <th>Post</th>
                                    <th>Contact Number</th>
                                    <th>Extension Number</th>
                                    <th>Image</th>
                                    @if(\Auth::user()->user_type == 1)
                                    <th></th>
                                    @endif
                                </tr>
                            </thead>

                            <tbody>
                                @if(isset($telephone))
                                    @foreach($telephone as $value)
                                        <tr>
                                            <td>{{$loop->iteration}}</td>
                                            <td>{{$value->name}}</td>
                                            <td>{{$value->department}}</td>
                                            <td>{{$value->post}}</td>
                                            <td>{{$value->contact}}</td>
                                            <td>{{$value->ext_number}}</td>
                                            <td>
                                                @if($value->staff_image != null)
                                                    <img src="{{ asset(STATIC_DIR.'storage/'.$value->staff_image) }}" class="img img-responsive" style="max-height:100px; max-width:100px;" alt="">
                                                @else
                                                    <img src="{{ asset(STATIC_DIR.'images/default.jpg') }}" class="img img-responsive" style="max-height:100px; max-width:100px;" alt="">
                                                @endif
                                            </td>
                                            @if(\Auth::user()->user_type == 1)
                                            <td>
                                                <a href="{{route('telephone.edit_telephone',$value->id)}}" class="btn default btn-xs blue-stripe" ><i class="glyphicon glyphicon-pencil"></i></a> &nbsp;
                                                <a href="#deleteTelephone" class="btn default btn-xs red-stripe" data-ids="{{ $value->id }}" data-toggle="modal" data-rel="delete" data-user="{{$value->name}}">
                                                    <i style="color:red;" class="glyphicon glyphicon-trash"></i>
                                                </a>

                                            </td>
                                            @endif
                                        </tr>
                                    @endforeach
                                @endif
                            </tbody>

                        </table>
                    </div>

                </div>
            </div>
        </div>

    </div>
    @include('pages.telephone.modal')
@endsection

@section('script')
    <script type="text/javascript" src="{{ asset(STATIC_DIR.'jquery/jquery.dataTables.min.js') }}"></script>
    <script>
        $(document).ready( function () {
            $('#myTable').dataTable( {
                "pageLength": 50,
                "lengthMenu": [ 10, 25, 50, 75, 100 ]
            } );
        } );

        $('#deleteTelephone').on('show.bs.modal', function (e) {
            //e.preventDefault();
            var button = $(e.relatedTarget);
            var ids = button.data('ids');
            var user = button.data('user');

            // Pass form reference to modal for submission on yes/ok
            var form = $(e.relatedTarget).closest('form');
            $(this).find('.modalfooter #confirm').data('form', form);
            $("#hidden_id").val(ids);
            $(".hidden_title").html(' "' + user + '" ');
        });


        $('#deleteTelephone').find('#confirm_yes').on('click', function () {

            //set csrf token
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            //fetching id
            var id = $("#hidden_id").val();

            $.ajax({
                type: "POST",
                url: "{{ route('telephone.delete_telephone') }}",
                headers: {
                    'XCSRFToken': $('meta[name="csrf-token"]').attr('content')
                },

                data: "id=" + id,
                success: function (msg) {
                    console.log(msg);
                    // alert(msg.error);
                    if(msg.error == false){
                        $("#deleteTelephone").modal("hide");
                        $('#showMessage').find('.success').show();
                        $("#showMessage").modal("show");
                    }
                    else
                    {
                        $("#deleteTelephone").modal("hide");
                        $('#showMessage').find('.error').show();
                        $("#showMessage").modal("show");
                    }
                    // window.location.reload();
                }
            });
        });

        $('#show_message').on('click', function () {
            window.location.reload();
        });
    </script>
@endsection

resources/views/pages/telephone/modal.blade.php
<div id="showMessage" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content" style="margin-top: 200px;">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title"><i class="fa fa-info-circle" id="icon-terminate" ></i> User Deleted
                </h4>
            </div>

            <div class="modal-body">
                <div class="error" style="display: none;">
                    <i class="fa fa-close"></i> &nbsp; Error While Deleting &nbsp;Telephone Information .
                </div>

                <div class="success" style="display: none;">
                    <i class="fa fa-check"></i> &nbsp; Telephone Info Deleted Successfully .
                </div>

            </div>
            <input type="hidden" id="hidden_id">
            <div class="modal-footer" style="text-align: center;">
                <button type="button" class="btn btn-danger green confirm_yes" id="show_message"><i class="icon-check"></i> Ok
                </button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
</div>

<div id="deleteTelephone" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content"  style="margin-top: 200px;">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title"><i class="fa fa-info-circle" id="icon-terminate" ></i> Delete Permanently
                </h4>
            </div>
            <div class="modal-body"> Do you want to delete <span class='hidden_title'>" "</span>?</div>
            <input type="hidden" id="hidden_id">
            <div class="modal-footer">
                <button type="button" class="btn btn-danger green confirm_yes" id="confirm_yes"><i class="icon-check"></i> Yes
                </button>
                <button type="button" class="btn btn-default" data-dismiss="modal"><i class="icon-close" id="icon-terminate"></i>
                    No
                </button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
</div>

resources/views/pages/telephone/register_telephone.blade.php
@extends('layouts.app')
@section('page-title')
    Register New Telephone
@stop
@section('css')
    <link rel="stylesheet" href="{{ asset(STATIC_DIR.'css/jquery.dataTables.min.css') }}">
    <link href="{{ asset(STATIC_DIR.'css/style.css')}}" rel="stylesheet" type="text/css"/>
@stop

@section('content')
    <div class="white-box">
        <div class="row">
            <div class="col-md-8">
                <h2>Employee Telephone Registration</h2>

                <form action="{{route('telephone.register_telephone')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label for="" class="control-label" >Name <span style="color: red;">*</span></label>
                        <input type="text" class="form-control" name="name" placeholder="Enter Employee Name" required value="{{old('name')}}" >
                        @if($errors->has('name'))
                            <span class="help-block" style="color:red;">
                                 {{$errors->first('name')}}
                            </span>
                        @endif

                    </div>

                    <div class="form-group">
                        <label for="" class="control-label">Department: <span style="color: red;">*</span></label>
                        <select name="department" class="form-control" id="exampleFormControlSelect1" required>
                            <option disabled="">Select One Department</option>
                            <option value="Software" {{ (old('department') == 'Software') ? "selected" : '' }}>Software </option>
                            <option value="Marketing" {{ (old('department') == 'Marketing') ? "selected" : '' }}>Marketing</option>
                            <option value="Human Resource" {{ (old('department') == 'Human Resource') ? "selected" : '' }}>Human Resource </option>
                            <option value="Account" {{ (old('department') == 'Account') ? "selected" : '' }}>Account</option>
                            <option value="Administration " {{ (old('department') == 'Administration') ? "selected" : '' }}>Administration </option>
                            <option value="Hardware" {{ (old('department') == 'Hardware') ? "selected" : '' }}>Hardware </option>
                        </select>

                        @if($errors->has('department'))
                            <span class="help-block" style="color:red;">
                                 {{$errors->first('department')}}
                            </span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label for="" class="control-label" >Post <span style="color: red;">*</span></label>
                        <input type="text" class="form-control" name="post"  placeholder="Enter Employee Post" required value="{{old('post')}}">
                        @if($errors->has('post'))
                            <span class="help-block" style="color:red;">
                                 {{$errors->first('post')}}
                            </span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label for=""  class="control-label">Contact Number <span style="color: red;">*</span></label>
                        <input type="number" class="form-control" name="contact" min="0" placeholder="Enter Contact Number" required value="{{old('contact')}}">
                        @if($errors->has('contact'))
                            <span class="help-block" style="color:red;">
                                 {{$errors->first('contact')}}
                            </span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label for="" class="control-label">Extension Number</label>
                        <input type="number" class="form-control" name="ext_number" min="0" placeholder="Enter Extension Number" value="{{old('ext_number')}}">
                        @if($errors->has('ext_number'))
                            <span class="help-block" style="color:red;">
                                 {{$errors->first('ext_number')}}
                            </span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label for="" class="control-label">Staff Image </label>
                        <input type="file" class="" name="staff_image">
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Submit" class="btn btn-primary">
                    </div>

                </form>
            </div>


        </div>
    </div>
@endsection

@section('script')
@endsection